language: node_js

node_js:
  - "16"

before_install:
  - echo "no before_install steps needed"

script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --config audit-ci.json; else npx audit-ci --config audit-ci.json || true; fi
  - npm run lint
  - npm test
  - if [[ "${TRAVIS_TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi

deploy:
  # Publish npm package when tagged as x.y.z release
  - provider: npm
    email: "${NPMJS_EMAIL}"
    api_key: "${NPMJS_API_KEY}"
    name: "${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
